### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-8th-edition#1]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** For the Astra militarum list. For scout and armored sentinels the autocannon upgrade should be 15 points on vehicles. It is currently set to 10 which is the infantry cost

**Comment by DrTobogganMD** [comment]
8th Edition is no longer being updated. All work is being done on 9th Edition. If you wish to update this data, please fork the repo and make the necessary updates.
