### ISSUE TITLE
[Anon] Bug report: Aeldari - Ynnari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-8th-edition#2]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Have a Farseer selected as 'Ynnari Warlord', however he cant be given a ynnari warlord trait, he can only receive the relics, the list of traits doesnt show up, even with box selected. Additionally, when farseer has 'ynnari warlord' box ticked, the error message saying i need a minimum of 1 warlord selected.

**Comment by DrTobogganMD** [comment]
8th Edition is no longer being updated. All work is being done on 9th Edition. If you wish to update this data, please fork the repo and make the necessary updates.
